/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ai-chat` | `/ai-chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/analysis` | `/analysis`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard/history` | `/dashboard/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import` | `/import`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import/panels/AIImportPanel` | `/import/panels/AIImportPanel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import/panels/APIImportPanel` | `/import/panels/APIImportPanel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import/panels/FileImportPanel` | `/import/panels/FileImportPanel`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/ai-chat` | `/ai-chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/analysis` | `/analysis`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard/history` | `/dashboard/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/import` | `/import`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/import/panels/AIImportPanel` | `/import/panels/AIImportPanel`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/import/panels/APIImportPanel` | `/import/panels/APIImportPanel`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/import/panels/FileImportPanel` | `/import/panels/FileImportPanel`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/ai-chat${`?${string}` | `#${string}` | ''}` | `/ai-chat${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/analysis${`?${string}` | `#${string}` | ''}` | `/analysis${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard/history${`?${string}` | `#${string}` | ''}` | `/dashboard/history${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/import${`?${string}` | `#${string}` | ''}` | `/import${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/import/panels/AIImportPanel${`?${string}` | `#${string}` | ''}` | `/import/panels/AIImportPanel${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/import/panels/APIImportPanel${`?${string}` | `#${string}` | ''}` | `/import/panels/APIImportPanel${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/import/panels/FileImportPanel${`?${string}` | `#${string}` | ''}` | `/import/panels/FileImportPanel${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ai-chat` | `/ai-chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/analysis` | `/analysis`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard/history` | `/dashboard/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import` | `/import`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import/panels/AIImportPanel` | `/import/panels/AIImportPanel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import/panels/APIImportPanel` | `/import/panels/APIImportPanel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/import/panels/FileImportPanel` | `/import/panels/FileImportPanel`; params?: Router.UnknownInputParams; };
    }
  }
}
